author: 'TODO'
date: 2023/06/19
modified: 2023/06/19

title: 'application_firewall_logging'
details: 'TODO'
description: |
    This Unified Log filter may be used to report on logging from the Application Firewall in macOS.
    This filter functions by monitoring logging from the com.apple.alf subsystem.

id: 7358c7ce-7099-4a80-a91b-ef42c4d64668
level: informational
status: experimental
logsource:
    product: macos
detection:
    selection:
        subsystem: 'com.apple.alf'
    condition: selection
falsepositives:
    - unknown
references:
    - https://github.com/builtin/jamfprotect/tree/main/unified_log_filters
ruletype: Hayabusa