author: 'TODO'
date: 2023/06/19
modified: 2023/06/19

title: 'configuration_profile_manual_install'
details: 'TODO'
description: |
    This Unified Log filter may be used to report on manual installations of a configuration profile by a user.  Automatic installations, such as those from an MDM server like Jamf Pro, will not be logged.
    This filter functions by monitoring logging from the ManagedClient subsystem, mdmclient process and the MDMDaemon category and event message containing a string known to indicate a successful, manual installation of a configuration profile.
id: d062318a-f54e-46e2-bd3d-549729ddf721
level: informational
status: experimental
logsource:
    product: macos
detection:
    selection:
        subsystem: 'com.apple.ManagedClient'
        process: 'mdmclient'
        category: 'MDMDaemon'
        eventMessage|contains|all:
            - 'Installed configuration profile:'
            - 'Source: Manual'
    condition: selection
falsepositives:
    - unknown
references:
    - https://github.com/builtin/jamfprotect/tree/main/unified_log_filters
ruletype: Hayabusa