author: 'TODO'
date: 2023/06/19
modified: 2023/06/19

title: 'modifications_dns_settings'
details: 'TODO'
description: |
    This Unified Log filter may be used to report on enabling or disabling the DNS Settings filter in Network Preferences.
    This filter functions by monitoring logging from the NetworkExtension subsystem, nehelper / nesessionmanager process and event message containing a string known to indicate enablement or disablement of the DNS Settings filter in Network System Preferences.
id: bcec7c4c-0c72-47dd-9ad6-fb43fefab032
level: informational
status: experimental
logsource:
    product: macos
detection:
    selection_1:
        subsystem: 'com.apple.networkextension'
        process: 'nehelper'
        eventMessage|contains: 'DNS settings are enabled'
    selection_2:
        subsystem: 'com.apple.networkextension'
        process: 'nesessionmanager'
        eventMessage|contains: 'status changed to disconnected, last stop reason Configuration was disabled'
    condition: selection_1 or selection_2
falsepositives:
    - unknown
references:
    - https://github.com/builtin/jamfprotect/tree/main/unified_log_filters
ruletype: Hayabusa

## modifications_dns_settings
##
## This Unified Log filter may be used to report on enabling or disabling the DNS Settings filter in Network Preferences.
## This filter functions by monitoring logging from the NetworkExtension subsystem, nehelper / nesessionmanager process and event message containing a string known to indicate enablement or disablement of the DNS Settings filter in Network System Preferences.
#
## Filter Predicate(s):
#
#subsystem == "com.apple.networkextension" and process == "nehelper" and eventMessage CONTAINS "DNS settings are enabled" OR subsystem == "com.apple.networkextension" and process == "nesessionmanager" and eventMessage contains "status changed to disconnected, last stop reason Configuration was disabled"'
#
## Example output:
#
#2022-XX-XX 14:00:17.4XXX27+XXXX 0x12ee26   Default     0x417f45             208    0    nehelper: (NetworkExtension) [com.apple.networkextension:] DNS settings are enabled
#
#2022-09-02 14:23:01.163871+0200 0x131146   Default     0x0                  764    0    nesessionmanager: [com.apple.networkextension:] NESMDNSSettingsSession[DNS Settings:1FEB95F4-5499-4BAA-AE37-9C8994F91C6D]: status changed to disconnected, last stop reason Configuration was disabled
#
## Copyright (c) 2022, Jamf Software, LLC. All rights reserved.