author: 'Fukusuke Takahashi'
date: 2023/06/19
modified: 2023/06/19

title: 'configuration_profile_manual_removal'
details: 'TODO'
description: 'TODO'

id: e13595f6-f442-4e3d-b1e7-56dde2f97ab5
level: informational
status: experimental
logsource:
  product: macos
detection:
  selection:
    process:"TODO"
  condition: selection
falsepositives:
  - unknown
references:
  - https://github.com/jamf/jamfprotect/tree/main/unified_log_filters
ruletype: Hayabusa

## configuration_profile_manual_removal
##
## This Unified Log filter may be used to report on manual removals of a configuration profile by a user.  Automatic removal, such as those from an MDM server like Jamf Pro, will not be logged.
## This filter functions by monitoring logging from the ManagedClient subsystem, mdmclient process and the MDMDaemon category and event message containing a string known to indicate a successful, manual removal of a configuration profile.
##
## Filter Predicate:
#
#subsystem == "com.apple.ManagedClient" AND process == "mdmclient" AND category == "MDMDaemon" and eventMessage CONTAINS "Removed configuration profile:" AND eventMessage CONTAINS "Source: Manual"
#
## Example output for a computer-level configuration profile
#
#2021-XX-XX XX:XX:51.732257+0100 XXXXXXX    Default     XXXXXXX              XXXX   0    mdmclient: [com.apple.ManagedClient:MDMDaemon] Removed configuration profile: Display Name Of Configuration Profile Installed (profile-identifier-here:profile-payload-UUID-here) for <Computer> (Source: Manual)